[package]
name = "spacy-alignments"
version = "0.9.1"
authors = ["Explosion <contact@explosion.ai>"]
edition = "2018"

[dependencies]
tokenizations = "0.4.2"

[dependencies.pyo3]
version = "^0.24.0"
features = ["extension-module"]

[lib]
name = "spacy_alignments"
crate-type = ["cdylib"]
